Profile the node as part of the initial connection
openflighthpc/flight-scheduler-daemon pull request #19
Opened 2020-11-19 20:05 UTC by WilliamMcCumstie

When the daemon starts in now uses `lshw` and `/proc/meminfo` to profile the node for cpu, gpu, and memory information. This is sent as part of the `CONNECTED` message.

Whilst re-connections will resend the information, the profiler will only run once. The daemon needs to be restarted for the profiler to run again.

2020-11-25 13:01 UTC, benarmston requested changes
This looks pretty good to me.  I like your use of test fixtures here :-)

Worthy of note is that correct profiling requires `lshw` to be ran as root.  As the daemon also needs to be able to execute processes as arbitrary users, there is already a requirement for the daemon to be ran as root.  So this is OK.

I've added a few comments that should be quick to address.

2020-11-25 13:01 UTC, benarmston commented on spec/batch_script_runner_spec.rb
> +  xit { should be_valid }
There are lots of specs that have been marked as pending.  Do these no longer work?  If they don't is that due to work on this branch?

2020-11-25 13:01 UTC, benarmston commented on lib/flight_scheduler/errors.rb
> +  class ProfilerError < RuntimeError; end
For errors that are only raised from a single class, we should standardise on namespacing them in the class that raises them.  Inheriting from a common base error is fine.

2020-11-25 13:01 UTC, benarmston commented on lib/flight_scheduler/application.rb
> +        memory: profiler.memory
Can we get some logging of the profile result.  Either here or in the profiler class.  Having that logging will make debugging issues much easier.

2020-11-25 13:01 UTC, benarmston commented on spec/fixtures/profiler/Standard_NC24s_v3.metadata.yaml
> +gpus: 5
Agreed. This is good enough for now.

2020-11-25 13:46 UTC, WilliamMcCumstie commented on spec/batch_script_runner_spec.rb
> +  xit { should be_valid }
All these specs where broken before this was implemented

2020-11-25 13:47 UTC, WilliamMcCumstie commented on spec/fixtures/profiler/Standard_NC24s_v3.metadata.yaml
> +gpus: 5
:+1:

2020-11-25 14:50 UTC, benarmston commented on spec/batch_script_runner_spec.rb
> +  xit { should be_valid }
Fair enough. I'll fix them and push a commit to this branch.  'Cos I just can't merge a branch with so many pending specs.  Apparently merging branches with broken specs is fine though /whistles/.

2020-11-25 15:16 UTC, benarmston commented on spec/batch_script_runner_spec.rb
> +  xit { should be_valid }
I've added a commit to get those tests working @WilliamMcCumstie .

2020-11-26 14:33 UTC, benarmston commented
Thanks for those changes @WilliamMcCumstie.  This looks good to me now.

2020-11-26 16:46 UTC, merged